name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: vmagent-nkd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        run: echo "Building application"

  test:
    name: Run Tests
    runs-on: vmagent-nkd
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests"

  lint:
    name: Lint Code
    runs-on: vmagent-nkd
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint code
        run: echo "Linting code"
